In [91]:
import numpy as np

#### 🧩 Nivel 1 – Fundamentos básicos

***1. Crea un array de 10 ceros y cámbiale el valor al cuarto elemento (índice 3) por 42.***

In [7]:
arr_ceros = np.array(np.zeros(10))
arr_ceros[3] = 42
arr_ceros

array([ 0.,  0.,  0., 42.,  0.,  0.,  0.,  0.,  0.,  0.])

***2. Genera un array de enteros del 10 al 49 y revierte su orden.***

In [22]:
arr_10_49 = np.arange(10,50)
arr_10_49_sort = np.sort(arr_10_49)[::-1] 
arr_10_49_sort

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

***3. Crea una matriz de 3x3 con valores del 0 al 8.***

In [ ]:
matriz_3_3 = np.arange(0,9).reshape(3,3)
matriz_3_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

***4. Encuentra los índices de los valores no cero de este array:***

np.array([0, 1, 2, 0, 4, 0])


In [32]:
arr_encontrar = np.array([0, 1, 2, 0, 4, 0])
indice = 0
for i in arr_encontrar:
    if i == 0:
        print(f'Indice: {indice} Elemento: {i}')
        indice += 1

Indice: 0 Elemento: 0
Indice: 1 Elemento: 0
Indice: 2 Elemento: 0


#### 📐 Nivel 2 – Álgebra lineal y estadísticas básicas

***6. Genera dos matrices 3x3 de enteros aleatorios y realiza su multiplicación matricial (@)***

In [35]:
matriz1 = np.arange(10,19).reshape(3,3)
matriz2 = np.arange(90,99).reshape(3,3)

matrix = matriz1 @ matriz2
matrix

array([[3075, 3108, 3141],
       [3912, 3954, 3996],
       [4749, 4800, 4851]])

***7. Crea una matriz 4x4 de números aleatorios y obtén la media de cada fila.***

In [43]:
matris_4_4 = np.arange(1,17).reshape(4,4)
matris_4_4.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

***8. Dada una matriz 5x5 con valores enteros del 0 al 24, normaliza sus valores para que estén entre 0 y 1.***

In [ ]:
matriz_original = np.arange(25).reshape(5, 5)

print("Matriz Original:")
print(matriz_original)

min_valor = np.min(matriz_original)
max_valor = np.max(matriz_original)

print(f"\nValor mínimo de la matriz: {min_valor}")
print(f"Valor máximo de la matriz: {max_valor}")

if (max_valor - min_valor) == 0:
    matriz_normalizada = np.zeros_like(matriz_original, dtype=float) 
else:
    matriz_normalizada = (matriz_original - min_valor) / (max_valor - min_valor)

print("\nMatriz Normalizada (valores entre 0 y 1):")
print(matriz_normalizada)

Matriz Original:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Valor mínimo de la matriz: 0
Valor máximo de la matriz: 24

Matriz Normalizada (valores entre 0 y 1):
[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


***9. Calcula la desviación estándar y varianza de un array de números aleatorios (longitud 1000).***

In [50]:
numeros_aleatorios = np.random.standard_normal(1000)
desv_estandar = numeros_aleatorios.std()
varianza = numeros_aleatorios.var()
print(f'Desviación Estándar: {desv_estandar:.3f}\nVarianza: {varianza:.3f}')

Desviación Estándar: 1.042
Varianza: 1.086


***10. Verifica si una matriz cuadrada es simétrica (matriz.T == matriz).***

In [51]:
def es_simetrica(matriz):
    if matriz.shape[0] != matriz.shape[1]:
        print("La matriz no es cuadrada, por lo tanto no puede ser simétrica.")
        return False

    return np.array_equal(matriz, matriz.T)

# Matriz simétrica
matriz_simetrica = np.array([[1, 2, 3],
                             [2, 4, 5],
                             [3, 5, 6]])
print("Matriz simétrica:")
print(matriz_simetrica)
print(f"¿Es simétrica? {es_simetrica(matriz_simetrica)}") # Debería ser True


# Matriz no simétrica
matriz_no_simetrica = np.array([[1, 2, 3],
                                 [4, 5, 6],
                                 [7, 8, 9]])
print("\nMatriz no simétrica:")
print(matriz_no_simetrica)
print(f"¿Es simétrica? {es_simetrica(matriz_no_simetrica)}") # Debería ser False

Matriz simétrica:
[[1 2 3]
 [2 4 5]
 [3 5 6]]
¿Es simétrica? True

Matriz no simétrica:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
¿Es simétrica? False


#### 🔄 Nivel 3 – Indexación, slicing avanzado y broadcasting

***11. Dado este array 5x5:***

arr = np.arange(25).reshape(5, 5)
* Extrae la submatriz del centro (3x3).
* Cambia los valores de la diagonal principal a -1 usando slicing.

In [79]:
arr = np.arange(25).reshape(5, 5)
print(f'Principal\n{arr}')
# print('\n')
arr_3_3 = np.array(((arr[1][1:4]),(arr[2][1:4]), (arr[3][1:4])))
print(f'\nSegunda\n{arr_3_3}')

indices_diag = np.diag_indices(arr.shape[0])
arr[indices_diag] = -1
print(f'\nTercer\n{arr}')

Principal
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Segunda
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]

Tercer
[[-1  1  2  3  4]
 [ 5 -1  7  8  9]
 [10 11 -1 13 14]
 [15 16 17 -1 19]
 [20 21 22 23 -1]]


***12. Dado un array aleatorio de 1,000 valores entre 0 y 100, reemplaza los valores > 90 por 90.***

In [ ]:
np.random.seed(42) # Para reproducibilidad, puedes quitar esta línea
array_aleatorio = np.random.uniform(0, 100, 1000)

print("Primeros 10 valores del array original (ejemplo):")
print(array_aleatorio[:10])

condicion = array_aleatorio > 90

array_aleatorio[condicion] = 90

print("\nPrimeros 10 valores del array modificado (ejemplo):")
print(array_aleatorio[:10])

Primeros 10 valores del array original (ejemplo):
[37.45401188 95.07143064 73.19939418 59.86584842 15.60186404 15.59945203
  5.80836122 86.61761458 60.11150117 70.80725778]

Primeros 10 valores del array modificado (ejemplo):
[37.45401188 90.         73.19939418 59.86584842 15.60186404 15.59945203
  5.80836122 86.61761458 60.11150117 70.80725778]


***14. Calcula el promedio móvil (window = 3) de este array:***
- arr = np.array([1, 2, 3, 4, 5, 6])


In [82]:
def moving_average(arr, window_size):
    if window_size <= 0:
        raise ValueError("Window size must be a positive integer.")
    if window_size > len(arr):
        raise ValueError("Window size cannot be greater than the array length.")

    weights = np.ones(window_size) / window_size

    return np.convolve(arr, weights, mode='valid')

arr = np.array([1, 2, 3, 4, 5, 6])
window = 3

ma_result = moving_average(arr, window)
print(f"Original array: {arr}")
print(f"Moving average (window={window}): {ma_result}")

Original array: [1 2 3 4 5 6]
Moving average (window=3): [2. 3. 4. 5.]


#### 🧠 Nivel 4 – Reto final estilo real

***14. Simula una matriz de datos de sensores de 30 días (30 filas x 24 columnas, cada columna representa una hora del día).***
* Calcula el promedio diario (por fila).
* Encuentra el día con mayor temperatura máxima.
* Reemplaza cualquier valor > 45°C con np.nan (simulando error de sensor).
* Imputa los NaN con la media de su respectiva columna.



In [102]:
import numpy as np

num_days = 30
hours_per_day = 24

np.random.seed(42)

mean_value = 25
std_dev = 5

# Simular datos de sensores con distribución normal
sensor_data_raw = np.random.normal(loc=mean_value, scale=std_dev, size=(num_days, hours_per_day))
sensor_data = np.clip(sensor_data_raw, a_min=0, a_max=50)

# Promedio de temperatura por día
promedio_fila = sensor_data.mean(axis=1)

# Obtener la temperatura máxima de cada día
max_temp_por_dia = sensor_data.max(axis=1)

# Día con la temperatura máxima
indice_dia_mayor_temp = np.argmax(max_temp_por_dia)
valor_temp_maxima = max_temp_por_dia[indice_dia_mayor_temp]

# Remplazar cualquier valor > 45 con np.nan
data = sensor_data.copy()
data[data > 45] = np.nan

# Imputar NaN
# Crear una copia para imputar los valores
data_imputada = data.copy()

# Calcular la media por columna (ignorando los NaN)
mean_per_col = np.nanmean(data_imputada, axis=0)

# Encontrar los índices donde hay NaN
nan_mask = np.isnan(data_imputada)

# Reemplazar NaNs con la media de su respectiva columna
data_imputada[nan_mask] = np.take(mean_per_col, np.where(nan_mask)[1])

# Mostrar resultados
print(f"Matriz de datos de sensores simulada ({num_days} días x {hours_per_day} horas):")
print("Promedio de temperatura por día:")
print(np.round(promedio_fila, 2))
print(f"\nEl día con la mayor temperatura fue el día {indice_dia_mayor_temp + 1} (índice {indice_dia_mayor_temp}), con una máxima de {valor_temp_maxima:.2f}°C")
print('\nMatriz con los valores replazados por np.nan > 45')
print(data)
print('\nDatos imputados')
print(data_imputada)

Matriz de datos de sensores simulada (30 días x 24 horas):
Promedio de temperatura por día:
[24.26 23.69 25.48 24.34 25.25 24.55 26.06 25.15 26.58 24.52 24.44 25.02
 25.73 26.21 23.85 26.01 25.08 26.   23.96 25.48 24.47 23.1  23.77 24.85
 25.46 26.84 23.4  25.27 25.03 24.63]

El día con la mayor temperatura fue el día 9 (índice 8), con una máxima de 44.26°C

Matriz con los valores replazados por np.nan > 45
[[27.48357077 24.30867849 28.23844269 32.61514928 23.82923313 23.82931522
  32.89606408 28.83717365 22.65262807 27.71280022 22.68291154 22.67135123
  26.20981136 15.43359878 16.37541084 22.18856235 19.9358444  26.57123666
  20.45987962 17.93848149 32.32824384 23.8711185  25.33764102 17.87625907]
 [22.27808638 25.55461295 19.24503211 26.87849009 21.99680655 23.54153125
  21.99146694 34.26139092 24.93251388 19.71144536 29.11272456 18.89578175
  26.04431798 15.20164938 18.35906976 25.98430618 28.6923329  25.85684141
  24.42175859 23.49448152 17.60739005 21.40077896 22.69680615 30.28561