In [3]:
import pandas as pd
import numpy as np 

Ejercicio 1: Manipulación de Arrays con NumPy

Crea un array NumPy de números enteros aleatorios entre 50 y 150 con forma (4,6). Luego realiza las siguientes operaciones:

* ✅ Encuentra el valor máximo y mínimo de cada fila.
* ✅ Calcula la media y la mediana de todo el array.
* ✅ Genera un nuevo array binario donde los valores mayores a la media sean 1 y los menores o iguales sean 0.
* ✅ Ordena el array de menor a mayor en cada fila.

In [4]:
# Creación del array aleatorio
array_aleatorio = np.random.randint(50, 151, size=(4, 6))
array_aleatorio

array([[111, 150, 145, 140, 150,  69],
       [150,  69,  70, 113,  75, 100],
       [ 54,  74,  66,  93,  55,  88],
       [108,  78, 100, 116, 122, 150]], dtype=int32)

In [6]:
# Encontrar el valor máximo y mínimo de cada fial
valor_minimo_filas = array_aleatorio.min(axis=1)
valor_maximo_filas = array_aleatorio.max(axis=1)
print(f'Valores Maximos: {valor_maximo_filas}    Valores Minimos: {valor_minimo_filas}')

Valores Maximos: [150 150  93 150]    Valores Minimos: [69 69 54 78]


In [4]:
# Calcular la media y la mediana de todo el array
media = array_aleatorio.mean()
mediana = np.median(array_aleatorio)
print(f'Media:{media}    Mediana:{mediana}')

Media:104.41666666666667    Mediana:106.5


In [ ]:
# Crear un array binario donde 1 sea si el valor es mayor a la media y 0 si es menor o igual
array_binario = np.where(array_aleatorio > media, 1, 0)
array_binario

array([[0, 0, 1, 1, 1, 1],
       [1, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 1],
       [1, 0, 0, 1, 0, 0]])

In [7]:
# Ordenar array de menor a mayor en cada fila
ordenar_array = np.sort(array_aleatorio, axis=1)
ordenar_array

array([[ 69, 111, 140, 145, 150, 150],
       [ 69,  70,  75, 100, 113, 150],
       [ 54,  55,  66,  74,  88,  93],
       [ 78, 100, 108, 116, 122, 150]], dtype=int32)

Ejercicio 2: Transformación y análisis de datos en Pandas
Crea un DataFrame con los siguientes datos:
* 'Producto': ['Laptop', 'Celular', 'Silla Gamer', 'Monitor', 'Escritorio'],
* 'Categoría': ['Electrónica', 'Electrónica', 'Muebles', 'Electrónica', 'Muebles'],
* 'Precio': [18000, 9000, 4500, 7500, 6000],
* 'Stock': [5, 12, 8, 10, 6],
* 'Fecha de Ingreso': ['2024-03-10', '2024-03-11', '2024-03-12', '2024-03-13', '2024-03-14']


Realiza las siguientes tareas:

* ✅ Agregar una nueva columna llamada "Descuento" donde:

    * Si el producto es de Electrónica, se aplica un 15% de descuento.

    * Si es de Muebles, se aplica un 10% de descuento.

* ✅ Filtrar solo los productos con un stock mayor a 5.
* ✅ Ordenar el DataFrame por Precio de mayor a menor.

In [7]:
# Crear DataFramse
data_1 = {
    'Producto': ['Laptop', 'Celular', 'Silla Gamer', 'Monitor', 'Escritorio'],
    'Categoría': ['Electrónica', 'Electrónica', 'Muebles', 'Electrónica', 'Muebles'],
    'Precio': [18000, 9000, 4500, 7500, 6000],
    'Stock': [5, 12, 8, 10, 6],
    'Fecha de Ingreso': ['2024-03-10', '2024-03-11', '2024-03-12', '2024-03-13', '2024-03-14']
}

df = pd.DataFrame(data_1)
df.head()

Producto    Categoría  Precio  Stock Fecha de Ingreso
0       Laptop  Electrónica   18000      5       2024-03-10
1      Celular  Electrónica    9000     12       2024-03-11
2  Silla Gamer      Muebles    4500      8       2024-03-12
3      Monitor  Electrónica    7500     10       2024-03-13
4   Escritorio      Muebles    6000      6       2024-03-14

In [8]:
# Agregar un nueva columnas "Descuentos"
df['Descuentos'] = df.apply(lambda row: row['Precio'] * 0.15 if row['Categoría'] == 'Electrónica' else row['Precio'] * 0.1 if row['Categoría'] == 'Muebles' else 0, axis=1)
df

Producto    Categoría  Precio  Stock Fecha de Ingreso  Descuentos
0       Laptop  Electrónica   18000      5       2024-03-10      2700.0
1      Celular  Electrónica    9000     12       2024-03-11      1350.0
2  Silla Gamer      Muebles    4500      8       2024-03-12       450.0
3      Monitor  Electrónica    7500     10       2024-03-13      1125.0
4   Escritorio      Muebles    6000      6       2024-03-14       600.0

In [11]:
# Filtrar los productos con stock mayor a 5
mask_stock = df['Stock'] > 5
df_stock_mayor_5 = df[mask_stock]
df_stock_mayor_5

Producto    Categoría  Precio  Stock Fecha de Ingreso  Descuentos
1      Celular  Electrónica    9000     12       2024-03-11      1350.0
2  Silla Gamer      Muebles    4500      8       2024-03-12       450.0
3      Monitor  Electrónica    7500     10       2024-03-13      1125.0
4   Escritorio      Muebles    6000      6       2024-03-14       600.0

In [13]:
# Ordenar DataFrame por precio de meayor a menor
df_ordenado = df.sort_values('Precio', ascending=False)
df_ordenado

Producto    Categoría  Precio  Stock Fecha de Ingreso  Descuentos
0       Laptop  Electrónica   18000      5       2024-03-10      2700.0
1      Celular  Electrónica    9000     12       2024-03-11      1350.0
3      Monitor  Electrónica    7500     10       2024-03-13      1125.0
4   Escritorio      Muebles    6000      6       2024-03-14       600.0
2  Silla Gamer      Muebles    4500      8       2024-03-12       450.0