In [4]:
import pandas as pd
import numpy as np

Ejercicio 1: Operaciones avanzadas con NumPy
Crea un array de números enteros aleatorios entre 10 y 100 con forma (5, 5) y realiza las siguientes operaciones:

1. Encuentra la suma de cada fila y de cada columna.
2. Calcula la desviación estándar y la varianza de todo el array.
3. Encuentra la posición (índice) del valor más alto y más bajo en el array.
4. Normaliza los valores del array entre 0 y 1 usando la siguiente fórmula:
    * “Xnorm​\=Xmax​−Xmin​X−Xmin​​”



In [5]:
# Creación del array 
array = np.random.randint(10,101,size=(5,5))
array

array([[66, 43, 30, 24, 50],
       [36, 67, 81, 43, 23],
       [57, 35, 47, 70, 66],
       [74, 15, 65, 96, 89],
       [14, 15, 70, 99, 31]], dtype=int32)

In [6]:
# Encontrar la suma de cada fila y de cada columna
suma_fila = array.sum(axis=1)
suma_fila

array([213, 250, 275, 339, 229])

In [7]:
# Calcular la desviación estandar y a varianza de todo el array
desviacion_estandar = array.std()
varianza = array.var()
print(f'''Desviación estandar: {desviacion_estandar} 
Varianza: {varianza}''')

Desviación estandar: 25.111399801683696 
Varianza: 630.5824


In [8]:
# Encontrar la posición (índice) del valor máximo y del valor mínimo
posicion_max = np.argmax(array)
posicion_min = np.argmin(array)

print(f'Posición del valor máximo: {posicion_max}')
print(f'Posición del valor mínimo: {posicion_min}')

Posición del valor máximo: 23
Posición del valor mínimo: 20


In [9]:
# Normalizar los valores del array entre 0 y 1 usado la fórmula de la normalización
minimo = array.min() # Mínimo valor del array
maximo = array.max() # Máximo valor del array
normalizado = (array - minimo) / (maximo - minimo)
normalizado

array([[0.61176471, 0.34117647, 0.18823529, 0.11764706, 0.42352941],
       [0.25882353, 0.62352941, 0.78823529, 0.34117647, 0.10588235],
       [0.50588235, 0.24705882, 0.38823529, 0.65882353, 0.61176471],
       [0.70588235, 0.01176471, 0.6       , 0.96470588, 0.88235294],
       [0.        , 0.01176471, 0.65882353, 1.        , 0.2       ]])

Ejercicio 2: Análisis de datos con Pandas
Crea un DataFrame con información de ventas en una tienda:

   * 'Producto': ['TV', 'Laptop', 'Celular', 'Tablet', 'Monitor'],
   * 'Precio': [12000, 18000, 9000, 6000, 7500],
   * 'Cantidad Vendida': [10, 5, 12, 8, 7],
   * 'Fecha Venta': ['2024-03-01', '2024-03-02', '2024-03-03', '2024-03-04', '2024-03-05']

Realiza las siguientes tareas:

1. Calcula la ganancia total por producto (Precio * Cantidad Vendida).
2. Agrega una nueva columna con el precio después de aplicar un descuento del 10%.
3. Encuentra el producto con mayor cantidad vendida y el de menor cantidad vendida.
4. Calcula la ganancia total de toda la tienda sumando las ganancias por producto.

In [10]:
data = {
    'Producto': ['TV', 'Laptop', 'Celular', 'Tablet', 'Monitor'],
    'Precio': [12000, 18000, 9000, 6000, 7500],
    'Cantidad Vendida': [10, 5, 12, 8, 7],
    'Fecha Venta': ['2024-03-01', '2024-03-02', '2024-03-03', '2024-03-04', '2024-03-05']
}
df = pd.DataFrame(data)
df.head()

Producto  Precio  Cantidad Vendida Fecha Venta
0       TV   12000                10  2024-03-01
1   Laptop   18000                 5  2024-03-02
2  Celular    9000                12  2024-03-03
3   Tablet    6000                 8  2024-03-04
4  Monitor    7500                 7  2024-03-05

In [11]:
# Calcular el total de la venta (Precio * Cantidad Vendida)
df['Total'] = df['Precio'] * df['Cantidad Vendida']
df

Producto  Precio  Cantidad Vendida Fecha Venta   Total
0       TV   12000                10  2024-03-01  120000
1   Laptop   18000                 5  2024-03-02   90000
2  Celular    9000                12  2024-03-03  108000
3   Tablet    6000                 8  2024-03-04   48000
4  Monitor    7500                 7  2024-03-05   52500

In [15]:
df['Descuento_10%'] = df['Precio'] * 0.10
df

Producto  Precio  Cantidad Vendida Fecha Venta   Total  Descuento_10%
0       TV   12000                10  2024-03-01  120000         1200.0
1   Laptop   18000                 5  2024-03-02   90000         1800.0
2  Celular    9000                12  2024-03-03  108000          900.0
3   Tablet    6000                 8  2024-03-04   48000          600.0
4  Monitor    7500                 7  2024-03-05   52500          750.0

In [35]:
producto_mas = df['Cantidad Vendida'].idxmax()
producto_menos = df['Cantidad Vendida'].idxmin()

print(f'Producto más vendido: {df["Producto"][producto_mas]} Cantidad: {df["Cantidad Vendida"][producto_mas]}')
print(f'Producto menos vendido: {df["Producto"][producto_menos]} Cantidad: {df["Cantidad Vendida"][producto_menos]}')


Producto más vendido: Celular Cantidad: 12
Producto menos vendido: Laptop Cantidad: 5


In [ ]:
# Ganacia total de toda la tienda (suma de la columna Total)
ganancia_total = df['Total'].sum()
print(f'Ganancia total: ${ganancia_total:.2f}')

Ganancia total: $418500.00
