In [2]:
import pandas as pd
import numpy as np

## Ejercicios de NumPy
1. Crea una matriz aleatoria de 5x5 con valores enteros entre 10 y 50 e imprime la suma de cada fila.
2. Calcula la desviación estándar de una matriz de 4x4 con números aleatorios entre 1 y 100.
3. Encuentra la posición del valor máximo y mínimo en una matriz de 6x6 generada con números aleatorios.
4. Filtra los valores pares de un arreglo de 20 elementos generados aleatoriamente entre 1 y 100.
5. Crea dos matrices de 3x3 y encuentra su producto punto.
6. Normaliza los valores de un arreglo de 10 elementos aleatorios entre 0 y 100 usando la fórmula:
    * “Xnorm​\=max(X)−min(X)X−min(X)​”
7. Convierte un arreglo de 1D a 2D con dimensiones 3x5.
8. Crea una máscara booleana en una matriz de 4x4 que devuelva True para valores mayores al promedio.
9. Genera una secuencia de números entre 0 y 1 con un paso de 0.1 usando np.linspace().
10. Encuentra el determinante y la inversa de una matriz de 3x3 generada aleatoriamente.

In [5]:
# Crear una matriz aleatroria de 5x5 con valores enteros entre 10 y 50 e imprime la suma de cada fila

# Crear la matriz
matriz = np.random.randint(10, 51, size=(5,5))
print(matriz)

suma_por_fila = matriz.sum(axis=1)
print(f'Suma de cada fila de la matriz: {suma_por_fila}')

[[26 14 31 47 48]
 [29 38 11 36 15]
 [47 30 39 32 35]
 [35 25 48 22 35]
 [43 20 14 34 12]]
Suma de cada fila de la matriz: [166 129 183 165 123]


In [7]:
# Calcular la desviación estandar de una matris de 4x4 con números aleatrorios entre 1 y 100

#Crear la matriz 4x4
matriz_4x4 = np.random.randint(1, 101, size=(4, 4))
desviacion_estandar = matriz_4x4.std()
print(matriz_4x4)
print(f'Desviación estandar de Matriz 4x4: {desviacion_estandar}')

[[33 41 37 36]
 [60 55 64  6]
 [27 95 78 27]
 [28 12 66 85]]
Desviación estandar de Matriz 4x4: 25.139299413468148


In [10]:
# Encuentra la posición del valor máximo y el mínimo en una matriz de 6x6 generada con números aleatorios.

#Crear la matriz 6x6
matriz_6x6 = np.random.randint(1,101,size=(6,6))
print(matriz_6x6)

valor_minimo_posicion = np.unravel_index(matriz_6x6.argmin(), matriz_6x6.shape)
valor_maximo_posicion = np.unravel_index(matriz_6x6.argmax(), matriz_6x6.shape)
print(f'Posición del valor mínimo: {valor_minimo_posicion}')
print(f'Posición del valor máximo: {valor_maximo_posicion}')

[[14 36 11 14  1 82]
 [30 92 44 37 89 74]
 [98 52 12 53 17 76]
 [64 16 16 27 67 59]
 [47 98 58 94 73 69]
 [15  4 48 27 59 35]]
Posición del valor mínimo: (np.int64(0), np.int64(4))
Posición del valor máximo: (np.int64(2), np.int64(0))


In [14]:
# Filtra losvalores pares de una arreglo de 20 elementos generados aleatoriamente entre 1 y 100
array = np.random.randint(1, 101, 20)
print(array)

valores_pares = array[array % 2 == 0]
print(f'Valores pares: {valores_pares}')

[95  1 55 20 26 85 68 62 44 82 31 66 99 80 47  5 67 59 88 95]
Valores pares: [20 26 68 62 44 82 66 80 88]


In [ ]:
# Crear 2 matirces de 3x3 y encuentra su producto punto.
matriz_3x3_1 = np.random.randint(1, 101, size=(3,3))
matriz_3x3_2 = np.random.randint(1, 101, size=(3,3))
producto_punto = np.dot(matriz_3x3_1, matriz_3x3_2)
print(producto_punto)

[[ 8833 14760  8938]
 [ 9930 17617 10402]
 [ 8805 15612  6626]]


In [17]:
arreglo_1 = np.random.randint(1, 101, 10)
min_arreglo_1 = arreglo_1.min()
max_arreglo_1 = arreglo_1.max()
arreglo_1_normalizado = arreglo_1 - min_arreglo_1 / max_arreglo_1 - min_arreglo_1
print(arreglo_1_normalizado)

[58.85858586 -0.14141414 22.85858586 44.85858586 14.85858586 26.85858586
 34.85858586 78.85858586 84.85858586 18.85858586]


In [19]:
# Converiti un arreglo de 1D a 2D con dimensiones 3x5
arreglo_1d = np.random.randint(1, 101, 15)
arreglo_2d = arreglo_1d.reshape(3, 5)
print(arreglo_1d)
print(arreglo_2d)

[78 23 41 98 46 38 77 63 56  9 92 55  2 60 37]
[[78 23 41 98 46]
 [38 77 63 56  9]
 [92 55  2 60 37]]


In [ ]:
# Crear una máscara booleana en una matriz 4x4
matriz_4_4 = np.random.randint(1, 101, size=(4, 4))
print(matriz_4_4)

promedio_matriz_4_4 = matriz_4_4.mean()
print(f'Promedio de matriz: {promedio_matriz_4_4}')

mascara_booleana = matriz_4_4 > promedio_matriz_4_4
print(mascara_booleana)

[[96 56 55 13]
 [13 26 56 46]
 [69 13 85 68]
 [98  9 20 30]]
Promedio de matriz: 47.0625
[[ True  True  True False]
 [False False  True False]
 [ True False  True  True]
 [ True False False False]]


In [27]:
# Genra una secuencia de números entre 0 y 1 con paso de 0.1 usando np.linspace()
secuencia = np.linspace(0, 1, num=11)
print(secuencia)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [30]:
# Encuentra el determinante y la inversa de una matriz 3x3 generada aleatoriamente.
matriz_3x3_2 = np.random.randint(1, 101, size=(3, 3))
determinante = np.linalg.det(matriz_3x3_2)
inversa = np.linalg.inv(matriz_3x3_2)  

print(matriz_3x3_2)
print(f'Determinante: {determinante}')
print(f'Inversa: {inversa}')

[[18 93 92]
 [91 81 30]
 [79 45 32]]
Determinante: -240017.9999999997
Inversa: [[-0.00517461 -0.00484964  0.01942354]
 [ 0.00225816  0.02788124 -0.03263089]
 [ 0.00959928 -0.02723546  0.02918531]]


Ejercicios de Pandas
1. Crea un DataFrame con 5 filas y 3 columnas con valores aleatorios entre 1 y 100. Renombra las columnas como "A", "B", "C" e imprime su media y mediana.
2. Carga un archivo CSV en un DataFrame e imprime las primeras 5 filas. Usa pd.read_csv().
3. Filtra los registros de un DataFrame donde una columna específica (ej. "Edad") sea mayor a 30 años.
4. Añade una nueva columna "Total" que sea la suma de otras dos columnas de un DataFrame.
5. Agrupa datos por una columna categórica y encuentra la media de cada grupo usando groupby().
6. Convierte una columna de fechas en formato "YYYY-MM-DD" a objetos datetime y extrae el año y mes.
7. Elimina los valores nulos de un DataFrame y rellena los vacíos con la media de la columna.
8. Crea una tabla pivote con datos ficticios de ventas, agrupando por "Categoría" y sumando "Ventas".
9. Ordena un DataFrame de mayor a menor en función de una columna "Precio".
10. Aplica una función personalizada a una columna para transformar sus valores (por ejemplo, convertir "USD" a "MXN").

In [ ]:
fila_A = np.random.randint(1, 101, 20)
fila_B = np.random.randint(1, 101, 20)
fila_C = np.random.randint(1, 101, 20)
data = {
    'A': fila_A,
    'B': fila_B,
    'C': fila_C
}
df = pd.DataFrame(data)

media = df.mean()
mediana = df.median()
print(f'Media: {media}')
print(f'Mediana: {mediana}')


Media: A    43.00
B    41.40
C    66.95
dtype: float64
Mediana: A    39.0
B    42.0
C    66.5
dtype: float64


In [ ]:
# Cargr un CSV y ver las primeras 5 filas
df_2 = pd.read_csv('../data/ejemplo.csv')
df_2.head(5)

A   B   C
0  82  56  37
1  57  32  95
2   8  27  67
3  85   8  47
4  10  33  65

In [ ]:
# Filtrar los registros 
data_3 = {
    'Nombre': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Edad': [25, 30, 22, 35, 28, 25, 30, 22, 35, 28],
    'Ahorro': [10000, 15000, 8000, 20000, 12000, 11000, 16000, 9000, 21000, 13000],
    'Fecha': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02', '2024-01-03',
              '2024-01-03', '2024-01-04', '2024-01-04', '2024-01-05', '2024-01-05'],
    'Categorias': ['A', 'B', 'A', 'C', 'B', 'A', 'B', 'A', 'C', 'B'],
    'Ventas': [100, 150, 80, 200, 120, 110, 160, 90, 210, 130]
}
df_3 = pd.DataFrame(data_3)
mayor_30 = df_3['Edad'] > 30
df_mayor_30 = df_3[mayor_30]
df_mayor_30

Nombre  Edad  Ahorro       Fecha Categorias  Ventas
3  David    35   20000  2024-01-02          C     200
8  David    35   21000  2024-01-05          C     210

In [ ]:
# Añadir una columna 'Total'
df_3['Total'] = df_3['Ahorro'] * df_3['Ventas']
df_3

Nombre  Edad  Ahorro       Fecha Categorias  Ventas    Total
0    Alice    25   10000  2024-01-01          A     100  1000000
1      Bob    30   15000  2024-01-01          B     150  2250000
2  Charlie    22    8000  2024-01-02          A      80   640000
3    David    35   20000  2024-01-02          C     200  4000000
4      Eve    28   12000  2024-01-03          B     120  1440000
5    Alice    25   11000  2024-01-03          A     110  1210000
6      Bob    30   16000  2024-01-04          B     160  2560000
7  Charlie    22    9000  2024-01-04          A      90   810000
8    David    35   21000  2024-01-05          C     210  4410000
9      Eve    28   13000  2024-01-05          B     130  1690000

In [ ]:
# Agrupar los datos y encontrar lo media de cada grupo 
agrupar_nombres = df_3.groupby('Nombre')['Ahorro'].mean()
agrupar_nombres

Nombre
Alice      10500.0
Bob        15500.0
Charlie     8500.0
David      20500.0
Eve        12500.0
Name: Ahorro, dtype: float64

In [14]:
# Convertir una columna fehca en formato "YYYY-MM-DD" a objeto datetime y extaer el año y mes
df_3['Fecha'] = pd.to_datetime(df_3['Fecha'])
df_3['Año'] = df_3['Fecha'].dt.year
df_3['Mes'] = df_3['Fecha'].dt.month   
df_3

Nombre  Edad  Ahorro      Fecha Categorias  Ventas    Total   Año  Mes
0    Alice    25   10000 2024-01-01          A     100  1000000  2024    1
1      Bob    30   15000 2024-01-01          B     150  2250000  2024    1
2  Charlie    22    8000 2024-01-02          A      80   640000  2024    1
3    David    35   20000 2024-01-02          C     200  4000000  2024    1
4      Eve    28   12000 2024-01-03          B     120  1440000  2024    1
5    Alice    25   11000 2024-01-03          A     110  1210000  2024    1
6      Bob    30   16000 2024-01-04          B     160  2560000  2024    1
7  Charlie    22    9000 2024-01-04          A      90   810000  2024    1
8    David    35   21000 2024-01-05          C     210  4410000  2024    1
9      Eve    28   13000 2024-01-05          B     130  1690000  2024    1

In [ ]:
# Eliminar valores nulos y llegarlos con la media de la columna
df_sin_nulos = df_3.dropna()
df_sin_nulos

# En mi caso no hay valores nulos ni valores vacio que llenar
df_rellenar = df_3.fillna(df_3.mean())
df_rellenar

In [18]:
# Crear una tabla pivote co datos ficticios de ventas, agrupados por categoria y sumando ventas
tabla_pivite = pd.pivot_table(df_3, values='Ventas', index='Categorias', aggfunc=np.sum)
tabla_pivite

C:\Users\52771\AppData\Local\Temp\ipykernel_21112\4246951305.py:2: FutureWarning: The provided callable <function sum at 0x0000025B731998A0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  tabla_pivite = pd.pivot_table(df_3, values='Ventas', index='Categorias', aggfunc=np.sum)


Ventas
Categorias        
A              380
B              560
C              410

In [ ]:
# Ordenar un DataFrame por ventas de mayor a menor (No cuento con la columna precio)
df_ordenado = df_3.sort_values('Ventas', ascending=False)
df_ordenado

Nombre  Edad  Ahorro      Fecha Categorias  Ventas    Total   Año  Mes
8    David    35   21000 2024-01-05          C     210  4410000  2024    1
3    David    35   20000 2024-01-02          C     200  4000000  2024    1
6      Bob    30   16000 2024-01-04          B     160  2560000  2024    1
1      Bob    30   15000 2024-01-01          B     150  2250000  2024    1
9      Eve    28   13000 2024-01-05          B     130  1690000  2024    1
4      Eve    28   12000 2024-01-03          B     120  1440000  2024    1
5    Alice    25   11000 2024-01-03          A     110  1210000  2024    1
0    Alice    25   10000 2024-01-01          A     100  1000000  2024    1
7  Charlie    22    9000 2024-01-04          A      90   810000  2024    1
2  Charlie    22    8000 2024-01-02          A      80   640000  2024    1

In [20]:
# Supongamos que la columna 'Ahorro' está en USD y queremos convertirla a MXN
tasa_conversion = 20  # 1 USD = 20 MXN
df_3['Ahorro_MXN'] = df_3['Ahorro'].apply(lambda x: x * tasa_conversion)
print(df_3[['Nombre', 'Ahorro', 'Ahorro_MXN']])

    Nombre  Ahorro  Ahorro_MXN
0    Alice   10000      200000
1      Bob   15000      300000
2  Charlie    8000      160000
3    David   20000      400000
4      Eve   12000      240000
5    Alice   11000      220000
6      Bob   16000      320000
7  Charlie    9000      180000
8    David   21000      420000
9      Eve   13000      260000
