In [255]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import random 
from datetime import datetime

In [2]:
# Crear un pequeño array 
data = np.array([[1,2,3,4],[5,6,7,8]])
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
# Realizar operaciones matematicas en el array
print(f'Operación 1 = {data * 10}')
print(f'Operación 2 = {data + data}')

Operación 1 = [[10 20 30 40]
 [50 60 70 80]]
Operación 2 = [[ 2  4  6  8]
 [10 12 14 16]]


Un ndarray es un contenedor genérico multidimencional para datos gomogéneos; es decir, todos los elementos deben ser del mismo tipo. Cada array tiene un shape, una tupla de indica el tamaño de cada dimensión, y un dtype, un objerto que describe el tipo de datos del array.

In [12]:
filas, columnas = data.shape
print(f'Filas:{filas}\nColumnas:{columnas}')

print(f'Tipo de datos en "data": {data.dtype}')

Filas:2
Columnas:4
Tipo de datos en "data": int64


La forma más sencilla de crear un arrya en mediente la función ***array***. Esta función acepta cualquier objeto similar a una secuencia (incluyendo otros arrays) y produce un nuevo array NumPy y conteniendo los datos pasados.

In [14]:
data1 = [1,2,3,4,5,6]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5, 6])

Las secuencias anidadas, una lista de lista de la misma longitud, sera convertidas en un array multidimensional.

In [16]:
data2 = [[1,2,3,4,5,6,],[7,8,9,10,11,12]]
arr2 = np.array(data2)
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Hay una serie de funciones adicionales para crear nuevos arrays. 
* **numpy.zeros** y **numpy.ones**: crean arrays de ceros y unos, respectivamente, con una determinada longitud o forma.
* **numpy.empty**: crea un array sin inicializar sus valores a ningún valor especial.

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
np.empty((2,3,2))

array([[[4.9e-324, 9.9e-324],
        [1.5e-323, 2.0e-323],
        [2.5e-323, 3.0e-323]],

       [[3.5e-323, 4.0e-323],
        [4.4e-323, 4.9e-323],
        [5.4e-323, 5.9e-323]]])

**np.arange** es un una versión con valores de la función range de python.

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

##### **Aritmética con Array NumPy**

Los array son importantes por que permiten operaciones en lotes con datos sin escribir bubles for. Los usuarios de NumPy llaman a estos vertorización. Cualquier operació aritmética entre arrays del mismo tamaño se aplica elemento por elemento.

Las operaciones aritméticas con escalares propagan el argumento escalar a cada elemento del array.

La comparación entre array del mismo tamaño producen array booleanos.

In [ ]:
# Operaciones aritméticas
arr1 * arr2

array([[ 1,  4,  9, 16, 25, 36],
       [ 7, 16, 27, 40, 55, 72]])

In [29]:
# Operaciones aritméticas con escalar
1 / arr2

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667],
       [0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
        0.08333333]])

In [30]:
# Array booleanos
arr1 > arr2

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False]])

El indexado de array en NumPy es un tema de gran profundidad, ya que hay muchas formas en las que se pueden querer seleccioanr un conjuinto de datos o elemento individuales. Los array unidimensionales son senciilos: a primera vista actuán de forma similar a las listas en Python.

In [34]:
arr3 = np.arange(10)
print(f'[5]: {arr3[5]}')
print(f'[5:8]{arr3[5:8]}')


[5]: 5
[5:8][5 6 7]


In [35]:
arr_slice = arr3[5:8]
arr_slice

array([5, 6, 7])

In [36]:
arr_slice[1] = 12345
arr3

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [38]:
arr_slice[:] = 64
arr3

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

##### Generar números pseudoaleatoria

In [40]:
samples = np.random.standard_normal(size=(4,4))
samples

array([[-0.93623933,  0.62657063,  1.45352753, -1.68253658],
       [ 0.26668342,  1.81895265,  1.3875335 , -1.2720463 ],
       [ 1.75284694, -0.44035323, -0.38308094, -0.60122777],
       [-0.07031809, -0.33558919, -0.31003375,  1.23365377]])

##### Explesar lógica condicional como operaciones de array

In [44]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True, False, True, True, False])

result = [(x if c else y)
            for x, y, c in zip(xarr,yarr,cond)]
result


[np.float64(1.1),
 np.float64(2.2),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.5)]

In [ ]:
# cond = condicióin, xarr = cunado cumple la condición, yarr = cuando no cumple la condición.
result = np.where(cond,xarr,yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

##### Métodos matemáticos y estadísticos
Es posible acceder a un conjunto de funciones matemáticas, que calculan estadísticas sobre un array completo o sobre los datos de un eje, como métodosde la clase array. Se pueden emplear agregaciones (a veces llamadas reducciones) como:
* sum
* mean
* std (desviación estándar)
o bien llamando al método de instacia de array o utilizando la función NumPy de máximo nivel. 

In [55]:
arr = np.random.standard_normal((5,4))
arr

print(f'arr.mean(): {arr.mean()}')
print(f'np.mean(): {np.mean(arr)}')

arr.mean(): 0.14885978056462496
np.mean(): 0.14885978056462496


In [65]:
col1 = np.arange(1,15)
col2 = np.arange(1,15)

dic = {
    'col1': col1,
    'col2': col2
}

df = pd.DataFrame(dic)
df

col1  col2
0      1     1
1      2     2
2      3     3
3      4     4
4      5     5
5      6     6
6      7     7
7      8     8
8      9     9
9     10    10
10    11    11
11    12    12
12    13    13
13    14    14

##### Métodos para Arrays Booleanos

Los valores booleanos son forzados al valor 1(True) y 0(False). De este modos, *sum* se utiliza a menudo como una forma de contar valores **True** en un array booleano 

In [67]:
arr = np.random.standard_normal(100)
valores_positivos = (arr > 0).sum()
valores_negativos = (arr <= 0).sum()
print(f'Positivos:{valores_positivos}\nNegativos:{valores_negativos}')

Positivos:55
Negativos:45


Dos métodos adicionales, *any*,*all*, son útiles especialmene para array booleanos. **any()** verifica si uno o varios valores de un array es True, mientras que **all()** comprueba que todos los valores son True.

In [72]:
bools = np.array([False, False, False, True, False])

print(bools.any())
print(bools.all())

True
False


Estos métodos funcionan también con arrays no booleanos, donde los elementos que no son ceros son tratados como True.

##### Ordenación

Los arrays puede ordenarse en el momento con el método sort.

In [80]:
arr = np.random.standard_normal(6)
print(f'Original: {arr}')

Original: [-0.19063484  0.76087368 -1.01335829 -0.689798   -0.22771521 -0.04089749]


In [81]:
arr.sort()
arr

array([-1.01335829, -0.689798  , -0.22771521, -0.19063484, -0.04089749,
        0.76087368])

##### **Crear datos aleatorios**

In [ ]:
vendedor_nombre = ['Said','Jared', 'Misra', 'Simba','Sam']
cantidad = np.arange(200,500)

dia = np.arange(1,30)
mes = np.arange(1,13)
anio = 2024

canal_venta = ['Tienda Física', 'Línea']
estado = ['Completado', 'Pendiente', 'Cancelado']

lista_numeros = [random.choice(cantidad) for _ in range(0,200)]
lista_nombres = [random.choice(vendedor_nombre) for _ in range(0,200)]
lista_canal_venta = [random.choice(canal_venta) for _ in range(0,200)]
lista_estado = [random.choice(estado) for _ in range(0,200)]
lista_fecha = []


for i in range(0,200):
    dia_aleatorio = random.choice(dia)
    mes_aleatorio = random.choice(mes)
    fecha = datetime(anio, mes_aleatorio, dia_aleatorio).date()
    lista_fecha.append(fecha)

data = {
    'Vendedor': lista_nombres,
    'Cantidad': lista_numeros,
    'estado': lista_estado,
    'canal_venta': lista_canal_venta, 
    'fecha': lista_fecha
}

df = pd.DataFrame(data)
df

Vendedor  Cantidad      estado    canal_venta       fecha
0        Sam       464   Pendiente  Tienda Física  2024-05-12
1      Simba       468  Completado  Tienda Física  2024-01-07
2      Jared       368   Pendiente          Línea  2024-07-20
3       Said       427   Pendiente  Tienda Física  2024-09-06
4      Simba       441   Cancelado          Línea  2024-06-18
..       ...       ...         ...            ...         ...
195      Sam       260   Pendiente  Tienda Física  2024-08-08
196      Sam       372  Completado          Línea  2024-03-05
197    Simba       466   Cancelado  Tienda Física  2024-11-27
198    Simba       302   Cancelado  Tienda Física  2024-07-21
199    Simba       428  Completado  Tienda Física  2024-10-11

[200 rows x 5 columns]

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Vendedor     200 non-null    object
 1   Cantidad     200 non-null    int64 
 2   estado       200 non-null    object
 3   canal_venta  200 non-null    object
 4   fecha        200 non-null    object
dtypes: int64(1), object(4)
memory usage: 7.9+ KB


In [165]:
df['fecha'] = pd.to_datetime(df['fecha'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   Vendedor     200 non-null    object        
 1   Cantidad     200 non-null    int64         
 2   estado       200 non-null    object        
 3   canal_venta  200 non-null    object        
 4   fecha        200 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 7.9+ KB


### 🟢 Nivel Básico (Exploración y estadísticas)

***1.-¿Cuál es la cantidad total vendida en todos el año?***

In [170]:
venta_2024 = df[df['fecha'].dt.year == 2024]
cantidad_total_2024 = venta_2024['Cantidad'].sum()
print(f'Cantidad Vendidad en el año 2024: ${cantidad_total_2024}')

Cantidad Vendidad en el año 2024: $69057


***2.-¿Qué vendedor tiene más ventas acumuladas?***

In [174]:
vendedor_mas_ventas = df.groupby('Vendedor')['Cantidad'].sum()
vendedor_mas_ventas.sort_values(ascending=False).head(1)

Vendedor
Simba    18160
Name: Cantidad, dtype: int64

***3.-¿Cuántas ventas hay por estado (Pendiente, Completado, Cancelado)?***

In [ ]:
ventas_estado = df['estado'].value_counts()
ventas_estado

estado
Cancelado     73
Completado    70
Pendiente     57
Name: count, dtype: int64

***4.-¿Cuál es la cantidad promedio por venta?***

In [180]:
promedio_venta = df['Cantidad'].mean()
print(f'Cantidad promedio por venta: ${promedio_venta:.2f}')

Cantidad promedio por venta: $345.29


***5.-¿Qué canal de venta tuvo más ventas?***

In [183]:
canal_venta = df['canal_venta'].value_counts()
canal_venta.sort_values(ascending=False).head(1)

canal_venta
Línea    103
Name: count, dtype: int64

In [ ]:
# Crear un columna mes
df['mes'] = df['fecha'].dt.month

# Crear una columna dia
df['dia'] = df['fecha'].dt.day

# Transformamos los numeros a meses
meses_nombre = {
    1: 'Enero',
    2: 'Febrero',
    3: 'Marzo',
    4: 'Abril',
    5: 'Mayo',
    6: 'Junio',
    7: 'Julio',
    8: 'Agosto',
    9: 'Septiembre',
    10: 'Octubre',
    11: 'Noviembre',
    12: 'Diciembre'
}


df['mes_nombre'] = df['mes'].replace(meses_nombre)
df


Vendedor  Cantidad      estado    canal_venta      fecha  mes  mes_nombre  \
0        Sam       464   Pendiente  Tienda Física 2024-05-12    5        Mayo   
1      Simba       468  Completado  Tienda Física 2024-01-07    1       Enero   
2      Jared       368   Pendiente          Línea 2024-07-20    7       Julio   
3       Said       427   Pendiente  Tienda Física 2024-09-06    9  Septiembre   
4      Simba       441   Cancelado          Línea 2024-06-18    6       Junio   
..       ...       ...         ...            ...        ...  ...         ...   
195      Sam       260   Pendiente  Tienda Física 2024-08-08    8      Agosto   
196      Sam       372  Completado          Línea 2024-03-05    3       Marzo   
197    Simba       466   Cancelado  Tienda Física 2024-11-27   11   Noviembre   
198    Simba       302   Cancelado  Tienda Física 2024-07-21    7       Julio   
199    Simba       428  Completado  Tienda Física 2024-10-11   10     Octubre   

     dia  
0     12  
1      7  
2     20  
3      6  
4     18  
..   ...  
195    8  
196    5  
197   27  
198   21  
199   11  

[200 rows x 8 columns]

### 🟡 Nivel Intermedio (Agrupamientos y fechas)

***6.-Ventas por mes: ¿Cuántas ventas hubo en cada mes?***

In [199]:
ventas_por_mes = df['mes_nombre'].value_counts()
ventas_por_mes.sort_values(ascending=False).head(1)

mes_nombre
Junio    26
Name: count, dtype: int64

***7.-Cantidad total vendida por canal y estado (tabla cruzada)?***

In [217]:
cantidad_total_canal_estado = df.groupby(['canal_venta','estado'])['Cantidad'].sum()
cantidad_total_canal_estado

canal_venta    estado    
Línea          Cancelado     12944
               Completado    12316
               Pendiente     10545
Tienda Física  Cancelado     12611
               Completado    11282
               Pendiente      9359
Name: Cantidad, dtype: int64

In [216]:
tabla_cruzada_ventas = pd.pivot_table(df,
                                      values='Cantidad',
                                      index='canal_venta',
                                      columns='estado',
                                      aggfunc='sum',
                                      fill_value=0) # Rellena los valores NaN con 0
print("\nTabla cruzada de cantidad total vendida por canal y estado (usando pivot_table):")
print(tabla_cruzada_ventas)


Tabla cruzada de cantidad total vendida por canal y estado (usando pivot_table):
estado         Cancelado  Completado  Pendiente
canal_venta                                    
Línea              12944       12316      10545
Tienda Física      12611       11282       9359


***8.-Ranking de vendedores por cantidad total vendida.***

In [225]:
vendedor_ranking = df.groupby('Vendedor')['Cantidad'].sum()
vendedor_ranking.sort_values(ascending=False)

Vendedor
Simba    18160
Said     13552
Misra    13446
Jared    12523
Sam      11376
Name: Cantidad, dtype: int64

***9.-Filtra las ventas del segundo trimestre (abril-junio).***

In [237]:
meses_filtro = ['Abril','Mayo','Junio']
ventas_abril_a_julio = df[df['mes_nombre'].isin(meses_filtro)]
ventas_abril_a_julio

Vendedor  Cantidad      estado    canal_venta      fecha  mes mes_nombre
0        Sam       464   Pendiente  Tienda Física 2024-05-12    5       Mayo
4      Simba       441   Cancelado          Línea 2024-06-18    6      Junio
5      Jared       402   Pendiente  Tienda Física 2024-06-21    6      Junio
13     Misra       448   Cancelado  Tienda Física 2024-06-14    6      Junio
14     Misra       491   Pendiente  Tienda Física 2024-05-27    5       Mayo
..       ...       ...         ...            ...        ...  ...        ...
170    Misra       297  Completado  Tienda Física 2024-06-13    6      Junio
175    Jared       467  Completado          Línea 2024-04-05    4      Abril
176    Simba       407  Completado          Línea 2024-04-25    4      Abril
179    Simba       480   Cancelado          Línea 2024-06-14    6      Junio
189    Misra       464   Pendiente  Tienda Física 2024-06-16    6      Junio

[63 rows x 7 columns]

***10.-¿Qué día tuvo la mayor cantidad de ventas realizadas?***

In [240]:
dia_mas_ventas = df.groupby(['dia'])['Cantidad'].sum()
dia_mas_ventas.sort_values(ascending=False).head(1)

dia
9    4596
Name: Cantidad, dtype: int64

### 🔵 Nivel Avanzado (Transformación y lógica de negocio)

***11.-Crea una columna mes a partir de la fecha, y agrupa ventas por mes y canal.***

In [242]:
# La columna mes ya existe
ventas_mes_canal = df.groupby(['mes','mes_nombre','canal_venta'])['Cantidad'].sum()
ventas_mes_canal

mes  mes_nombre  canal_venta  
1    Enero       Línea            4083
                 Tienda Física    3100
2    Febrero     Línea            4584
                 Tienda Física    3265
3    Marzo       Línea            3045
                 Tienda Física    1899
4    Abril       Línea            3457
                 Tienda Física    2610
5    Mayo        Línea            3480
                 Tienda Física    2888
6    Junio       Línea            4424
                 Tienda Física    4723
7    Julio       Línea            2416
                 Tienda Física    3407
8    Agosto      Línea            2941
                 Tienda Física    2537
9    Septiembre  Línea            2654
                 Tienda Física    4593
10   Octubre     Línea            2247
                 Tienda Física    1325
11   Noviembre   Línea            2474
                 Tienda Física    2905
Name: Cantidad, dtype: int64

***12.-Agrega una columna objetivo_logrado si la cantidad es mayor a 400.***

In [243]:
df['objetivo_logrado'] = np.where(df['Cantidad'] > 400, 'Logrado', 'No logrado')
df

Vendedor  Cantidad      estado    canal_venta      fecha  mes  mes_nombre  \
0        Sam       464   Pendiente  Tienda Física 2024-05-12    5        Mayo   
1      Simba       468  Completado  Tienda Física 2024-01-07    1       Enero   
2      Jared       368   Pendiente          Línea 2024-07-20    7       Julio   
3       Said       427   Pendiente  Tienda Física 2024-09-06    9  Septiembre   
4      Simba       441   Cancelado          Línea 2024-06-18    6       Junio   
..       ...       ...         ...            ...        ...  ...         ...   
195      Sam       260   Pendiente  Tienda Física 2024-08-08    8      Agosto   
196      Sam       372  Completado          Línea 2024-03-05    3       Marzo   
197    Simba       466   Cancelado  Tienda Física 2024-11-27   11   Noviembre   
198    Simba       302   Cancelado  Tienda Física 2024-07-21    7       Julio   
199    Simba       428  Completado  Tienda Física 2024-10-11   10     Octubre   

     dia objetivo_logrado  
0     12          Logrado  
1      7          Logrado  
2     20       No logrado  
3      6          Logrado  
4     18          Logrado  
..   ...              ...  
195    8       No logrado  
196    5       No logrado  
197   27          Logrado  
198   21       No logrado  
199   11          Logrado  

[200 rows x 9 columns]

***13.-Calcula el porcentaje de ventas canceladas por cada vendedor.***

In [252]:
mask_cancelado = df['estado'] == 'Cancelado'
df_cancelado = df[mask_cancelado]
ventas_canceladas = df_cancelado.groupby('Vendedor')['Cantidad'].sum()
ventas_canceladas

Vendedor
Jared    4575
Misra    4519
Said     5046
Sam      4094
Simba    7321
Name: Cantidad, dtype: int64

***14.-Simula precios por unidad aleatorios y calcula una columna monto_total = cantidad × precio_unitario.***

In [253]:
# No existe una columna "cantidaa" por lo que ocupare la de dia para simular cantidad
df['monto_total'] = df['Cantidad'] * df['dia']
df

Vendedor  Cantidad      estado    canal_venta      fecha  mes  mes_nombre  \
0        Sam       464   Pendiente  Tienda Física 2024-05-12    5        Mayo   
1      Simba       468  Completado  Tienda Física 2024-01-07    1       Enero   
2      Jared       368   Pendiente          Línea 2024-07-20    7       Julio   
3       Said       427   Pendiente  Tienda Física 2024-09-06    9  Septiembre   
4      Simba       441   Cancelado          Línea 2024-06-18    6       Junio   
..       ...       ...         ...            ...        ...  ...         ...   
195      Sam       260   Pendiente  Tienda Física 2024-08-08    8      Agosto   
196      Sam       372  Completado          Línea 2024-03-05    3       Marzo   
197    Simba       466   Cancelado  Tienda Física 2024-11-27   11   Noviembre   
198    Simba       302   Cancelado  Tienda Física 2024-07-21    7       Julio   
199    Simba       428  Completado  Tienda Física 2024-10-11   10     Octubre   

     dia objetivo_logrado  monto_total  
0     12          Logrado         5568  
1      7          Logrado         3276  
2     20       No logrado         7360  
3      6          Logrado         2562  
4     18          Logrado         7938  
..   ...              ...          ...  
195    8       No logrado         2080  
196    5       No logrado         1860  
197   27          Logrado        12582  
198   21       No logrado         6342  
199   11          Logrado         4708  

[200 rows x 10 columns]

***15.-Agrega una columna con la categoría de venta:***

* Alta si la cantidad > 450
* Media si está entre 350–450
* Baja si < 350


In [254]:
# Definir las condiciones
condiciones = [
    df['Cantidad'] > 450,                             
    (df['Cantidad'] >= 350) & (df['Cantidad'] <= 450)
]

# Definir las opciones correspondientes a cada condición
opciones = ['Alta', 'Media']

# Crear la columna 'venta' usando np.select()
# El valor 'Baja' será el default si ninguna de las condiciones anteriores se cumple
df['venta'] = np.select(condiciones, opciones, default='Baja')

df

Vendedor  Cantidad      estado    canal_venta      fecha  mes  mes_nombre  \
0        Sam       464   Pendiente  Tienda Física 2024-05-12    5        Mayo   
1      Simba       468  Completado  Tienda Física 2024-01-07    1       Enero   
2      Jared       368   Pendiente          Línea 2024-07-20    7       Julio   
3       Said       427   Pendiente  Tienda Física 2024-09-06    9  Septiembre   
4      Simba       441   Cancelado          Línea 2024-06-18    6       Junio   
..       ...       ...         ...            ...        ...  ...         ...   
195      Sam       260   Pendiente  Tienda Física 2024-08-08    8      Agosto   
196      Sam       372  Completado          Línea 2024-03-05    3       Marzo   
197    Simba       466   Cancelado  Tienda Física 2024-11-27   11   Noviembre   
198    Simba       302   Cancelado  Tienda Física 2024-07-21    7       Julio   
199    Simba       428  Completado  Tienda Física 2024-10-11   10     Octubre   

     dia objetivo_logrado  monto_total  venta  
0     12          Logrado         5568   Alta  
1      7          Logrado         3276   Alta  
2     20       No logrado         7360  Media  
3      6          Logrado         2562  Media  
4     18          Logrado         7938  Media  
..   ...              ...          ...    ...  
195    8       No logrado         2080   Baja  
196    5       No logrado         1860  Media  
197   27          Logrado        12582   Alta  
198   21       No logrado         6342   Baja  
199   11          Logrado         4708  Media  

[200 rows x 11 columns]

### 🔴 Nivel Experto (Storytelling y visualización)

***16.-¿Cómo se comportan las ventas a lo largo del año? Grafica una serie temporal.***

In [290]:
# Lista con los meses ordenados cronologicamente
orden_meses = [
    'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
    'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
]

# Convertir la columna 'mes_nombre' a tipo categórico ordenado
df['mes_nombre'] = pd.Categorical(df['mes_nombre'], categories=orden_meses, ordered=True)

largo_del_anio = df.groupby(['mes_nombre'])['Cantidad'].sum()
ass = df.groupby(['mes'])['Cantidad'].sum()
print(largo_del_anio)
print(ass)
# largo_del_anio
# print(f'index: {largo_del_anio.index}')
# print('\n')
# print(f'value: {largo_del_anio.values}')

# plt.figure(figsize=(15,8))
# plt.plot(largo_del_anio.index, largo_del_anio.values)
# plt.show()

mes_nombre
Enero         7183
Febrero       7849
Marzo         4944
Abril         6067
Mayo          6368
Junio         9147
Julio         5823
Agosto        5478
Septiembre    7247
Octubre       3572
Noviembre     5379
Diciembre        0
Name: Cantidad, dtype: int64
mes
1     7183
2     7849
3     4944
4     6067
5     6368
6     9147
7     5823
8     5478
9     7247
10    3572
11    5379
Name: Cantidad, dtype: int64


C:\Users\52771\AppData\Local\Temp\ipykernel_10332\1064103317.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  largo_del_anio = df.groupby(['mes_nombre'])['Cantidad'].sum()
