In [1]:
import numpy as np

In [2]:
# Crear un pequeño array 
data = np.array([[1,2,3,4],[5,6,7,8]])
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
# Realizar operaciones matematicas en el array
print(f'Operación 1 = {data * 10}')
print(f'Operación 2 = {data + data}')

Operación 1 = [[10 20 30 40]
 [50 60 70 80]]
Operación 2 = [[ 2  4  6  8]
 [10 12 14 16]]


Un ndarray es un contenedor genérico multidimencional para datos gomogéneos; es decir, todos los elementos deben ser del mismo tipo. Cada array tiene un shape, una tupla de indica el tamaño de cada dimensión, y un dtype, un objerto que describe el tipo de datos del array.

In [12]:
filas, columnas = data.shape
print(f'Filas:{filas}\nColumnas:{columnas}')

print(f'Tipo de datos en "data": {data.dtype}')

Filas:2
Columnas:4
Tipo de datos en "data": int64


La forma más sencilla de crear un arrya en mediente la función ***array***. Esta función acepta cualquier objeto similar a una secuencia (incluyendo otros arrays) y produce un nuevo array NumPy y conteniendo los datos pasados.

In [14]:
data1 = [1,2,3,4,5,6]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5, 6])

Las secuencias anidadas, una lista de lista de la misma longitud, sera convertidas en un array multidimensional.

In [16]:
data2 = [[1,2,3,4,5,6,],[7,8,9,10,11,12]]
arr2 = np.array(data2)
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Hay una serie de funciones adicionales para crear nuevos arrays. 
* **numpy.zeros** y **numpy.ones**: crean arrays de ceros y unos, respectivamente, con una determinada longitud o forma.
* **numpy.empty**: crea un array sin inicializar sus valores a ningún valor especial.

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
np.empty((2,3,2))

array([[[4.9e-324, 9.9e-324],
        [1.5e-323, 2.0e-323],
        [2.5e-323, 3.0e-323]],

       [[3.5e-323, 4.0e-323],
        [4.4e-323, 4.9e-323],
        [5.4e-323, 5.9e-323]]])

**np.arange** es un una versión con valores de la función range de python.

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

##### **Aritmética con Array NumPy**

Los array son importantes por que permiten operaciones en lotes con datos sin escribir bubles for. Los usuarios de NumPy llaman a estos vertorización. Cualquier operació aritmética entre arrays del mismo tamaño se aplica elemento por elemento.

Las operaciones aritméticas con escalares propagan el argumento escalar a cada elemento del array.

La comparación entre array del mismo tamaño producen array booleanos.

In [ ]:
# Operaciones aritméticas
arr1 * arr2

array([[ 1,  4,  9, 16, 25, 36],
       [ 7, 16, 27, 40, 55, 72]])

In [29]:
# Operaciones aritméticas con escalar
1 / arr2

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667],
       [0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
        0.08333333]])

In [30]:
# Array booleanos
arr1 > arr2

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False]])

El indexado de array en NumPy es un tema de gran profundidad, ya que hay muchas formas en las que se pueden querer seleccioanr un conjuinto de datos o elemento individuales. Los array unidimensionales son senciilos: a primera vista actuán de forma similar a las listas en Python.

In [34]:
arr3 = np.arange(10)
print(f'[5]: {arr3[5]}')
print(f'[5:8]{arr3[5:8]}')


[5]: 5
[5:8][5 6 7]


In [35]:
arr_slice = arr3[5:8]
arr_slice

array([5, 6, 7])

In [36]:
arr_slice[1] = 12345
arr3

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [38]:
arr_slice[:] = 64
arr3

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

##### Generar números pseudoaleatoria

In [40]:
samples = np.random.standard_normal(size=(4,4))
samples

array([[-0.93623933,  0.62657063,  1.45352753, -1.68253658],
       [ 0.26668342,  1.81895265,  1.3875335 , -1.2720463 ],
       [ 1.75284694, -0.44035323, -0.38308094, -0.60122777],
       [-0.07031809, -0.33558919, -0.31003375,  1.23365377]])

##### Explesar lógica condicional como operaciones de array

In [44]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True, False, True, True, False])

result = [(x if c else y)
            for x, y, c in zip(xarr,yarr,cond)]
result


[np.float64(1.1),
 np.float64(2.2),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.5)]

In [ ]:
# cond = condicióin, xarr = cunado cumple la condición, yarr = cuando no cumple la condición.
result = np.where(cond,xarr,yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

##### Métodos matemáticos y estadísticos
Es posible acceder a un conjunto de funciones matemáticas, que calculan estadísticas sobre un array completo o sobre los datos de un eje, como métodosde la clase array. Se pueden emplear agregaciones (a veces llamadas reducciones) como:
* sum
* mean
* std (desviación estándar)
o bien llamando al método de instacia de array o utilizando la función NumPy de máximo nivel. 

In [55]:
arr = np.random.standard_normal((5,4))
arr

print(f'arr.mean(): {arr.mean()}')
print(f'np.mean(): {np.mean(arr)}')

arr.mean(): 0.14885978056462496
np.mean(): 0.14885978056462496


In [61]:
import pandas as pd

In [65]:
col1 = np.arange(1,15)
col2 = np.arange(1,15)

dic = {
    'col1': col1,
    'col2': col2
}

df = pd.DataFrame(dic)
df

col1  col2
0      1     1
1      2     2
2      3     3
3      4     4
4      5     5
5      6     6
6      7     7
7      8     8
8      9     9
9     10    10
10    11    11
11    12    12
12    13    13
13    14    14

##### Métodos para Arrays Booleanos

Los valores booleanos son forzados al valor 1(True) y 0(False). De este modos, *sum* se utiliza a menudo como una forma de contar valores **True** en un array booleano 

In [67]:
arr = np.random.standard_normal(100)
valores_positivos = (arr > 0).sum()
valores_negativos = (arr <= 0).sum()
print(f'Positivos:{valores_positivos}\nNegativos:{valores_negativos}')

Positivos:55
Negativos:45


Dos métodos adicionales, *any*,*all*, son útiles especialmene para array booleanos. **any()** verifica si uno o varios valores de un array es True, mientras que **all()** comprueba que todos los valores son True.

In [72]:
bools = np.array([False, False, False, True, False])

print(bools.any())
print(bools.all())

True
False


Estos métodos funcionan también con arrays no booleanos, donde los elementos que no son ceros son tratados como True.

##### Ordenación

Los arrays puede ordenarse en el momento con el método sort.

In [80]:
arr = np.random.standard_normal(6)
print(f'Original: {arr}')

Original: [-0.19063484  0.76087368 -1.01335829 -0.689798   -0.22771521 -0.04089749]


In [81]:
arr.sort()
arr

array([-1.01335829, -0.689798  , -0.22771521, -0.19063484, -0.04089749,
        0.76087368])